name: simpleTrade
version: 1.0.0
main: cn.m1arcleur.simpletrade.SimpleTrade
api-version: '1.13'
authors: [ MiracleUR ]
depend: [ Vault ]
softdepend:
  - PlaceholderAPI
commands:
  simpleTrade:
    description: have a trade
    permission: ""
    permission-message: "你执行不了啊awa"
  simpleview:
    description: have a simpleView
    permission: ""
    permission-message: "你执行不了啊awa"
  simpleaccept:
    description: have a simpleAccept
    permission: ""
    permission-message: "你执行不了啊awa"
  simplerefuse:
    description: have a simpleRefuse
    permission: ""
    permission-message: "你执行不了啊awa"
  tradecancel:
    description: have a tradecancel
    permission: ""
    permission-message: "你执行不了啊awa"